[package]
name = "mytToken"
version = "0.0.0"
[addresses]
StarcoinFramework = "0x1"
MyTokenAddr = "0x1641b99d5c1a94bfcbb538fc9a89c6d8"
XUSDTAddr ="0x1641b99d5c1a94bfcbb538fc9a89c6d8"
 

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}